runtime! archlinux.vim

set viminfo+=n~/.config/viminfo

:highlight ExtraWhitespace ctermbg=red guibg=red
:match ExtraWhitespace /\s\+$/

syntax on
set encoding=utf-8
set tabstop=2
set number relativenumber
set visualbell
set t_vb=
set bg=light
set go=a
set nohlsearch
set showcmd

nnoremap <C-s> :w<CR>
nnoremap <C-Z> u
nnoremap <C-Y> <C-R>
nnoremap <BS> i<BS>
nnoremap <C-x> :q<CR>

inoremap <C-s> <Esc>:w<CR>
inoremap <C-Z> <C-O>u
inoremap <C-Y> <C-O><C-R>
