#!/bin/sh

# this has to be in xinitrc, otherwise firefox doesn't read it
export MOZ_USE_XINPUT2=1

# this fixes the pinentry appearing in the login tty
gpg-connect-agent updatestartuptty /bye >/dev/null

~/.local/bin/hotkeys/unfuck-keyboard.sh
xrdb -merge ~/.config/x11/Xresourses
xrandr --dpi 144 # does this actually do anything??
exec i3
