Section "InputClass"
  Identifier "keyboard defaults"
  MatchIsKeyboard "on"

  Option "XkbLayout" "us,ru"
  Option "XKbOptions" "grp:toggle,grp:caps_toggle,grp:alt_shift_toggle,grp_led:caps,compose:caps"
EndSection
