#!/bin/sh

# enable color support of ls
[ -x "$(command -v dircolors)" ] && eval $( [ -e ~/.config/dircolors ] && dircolors -b ~/.config/dircolors || dircolors -b )
[ -x "$(command -v curl)" ] && alias wget='curl -O'

alias cls='clear'
alias where='whereis'
alias whitch='which'
alias witch='which'
alias py='python'
alias gits='git status'
alias ls='ls --color=auto --group-directories-first'
alias la='ls -lAuGh --file-type'
alias ffmpeg='ffmpeg -hide_banner'
alias ffprobe='ffprobe -hide_banner'
alias grep='grep --color=auto'
alias R='R --quiet --no-save'
alias ln='ln --symbolic --interactive --verbose'
alias cp='cp --interactive --verbose'
alias mv='mv --interactive --verbose'
alias rm='rm --verbose'
alias mkd='mkdir --parents --verbose'
