#!/bin/sh

# enable color support of ls
[ -x "$(command -v dircolors)" ] && eval $( [ -e ~/.config/dircolors ] && dircolors -b ~/.config/dircolors || dircolors -b )
[ -x "$(command -v curl)" ] && alias wget='curl -LO'
[ -x "$(command -v batcat)" ] && alias bat='batcat'

mkd () {
  mkdir --parents --verbose "$@"
  cd "$@"
}

alias cls='clear'
alias where='whereis'
alias whitch='which'
alias witch='which'
alias py='python3'
alias gits='git status'
alias gitl='git log --graph --all'
alias ls='ls --color=auto --group-directories-first'
alias la='ls -lAuGh --file-type'
alias ffmpeg='ffmpeg -hide_banner'
alias ffprobe='ffprobe -hide_banner'
alias ffplay='ffplay -hide_banner'
alias grep='grep --color=auto'
alias R='R --quiet --no-save'
alias ln='ln --symbolic --interactive --verbose'
alias cp='cp --interactive --verbose'
alias mv='mv --interactive --verbose'
alias rm='rm --verbose'
alias df='df --human-readable'
alias yt='youtube-dl --add-metadata --ignore-errors'
alias yta='yt -x -f bestaudio/best'
alias ytx='yta'
alias h='history | less +G'
alias tree='tree --gitignore'
alias grasstouch='install --mode=644 -D /dev/null'
