#!/bin/sh

# This file sets environmental variables.

# Return if we alredy have all the vars.
[ -z "$TERMINAL" ] || return

# set PATH so it includes user's private bin if it exists
[ -d "$HOME/.local/bin" ] && PATH="$HOME/.local/bin:$PATH"
[ -d "$HOME/bin" ] && PATH="$HOME/bin:$PATH"
[ -d "$HOME/.cargo/bin" ] && PATH="$HOME/.cargo/bin:$PATH"
export PATH

if command -v locale >/dev/null; then
  export LC_TIME="ru_RU.UTF-8"
  export LC_NUMERIC="en_US.UTF-8"
  export LC_ALL=
fi

export EDITOR="nano"
export TERMINAL="st"
[ -z "$DISPLAY" ] && export DISPLAY=127.0.0.1:0
[ -z "$PULSE_SERVER" ] && export PULSE_SERVER=tcp:127.0.0.1
export NODE_PATH=/usr/lib/node_modules:/usr/local/lib/node_modules
export BAT_PAGER="less -RS"

# ~/ Clean-up:
# export HISTFILE="$HOME/.config/bash_history"
export RLWRAP_HOME="$HOME/.config"
export LESSHISTFILE="$HOME/.config/less_history"
export INPUTRC="$HOME/.config/inputrc"
export ZDOTDIR="$HOME/.config/zsh"
export NODE_REPL_HISTORY="$HOME/.config/node_repl_history"
export NPM_CONFIG_USERCONFIG="$HOME/.config/npmrc"

# less/man colors
export LESS=-R
export LESS_TERMCAP_mb=$'\x1b[1;31m'
export LESS_TERMCAP_md=$'\x1b[1;36m'
export LESS_TERMCAP_me=$'\x1b[0m'
export LESS_TERMCAP_so=$'\x1b[1;44;33m'
export LESS_TERMCAP_se=$'\x1b[0m'
export LESS_TERMCAP_us=$'\x1b[1;32m'
export LESS_TERMCAP_ue=$'\x1b[0m'
