#!/bin/sh

# This file sets environmental variables.

# Return if we already have all the vars.
[ -z "$TERMINAL" ] || return

# set PATH so it includes user's private bin if it exists
[ -d "$HOME/.local/bin" ] && PATH="$HOME/.local/bin:$PATH"
[ -d "$HOME/.local/bin/hotkeys" ] && PATH="$HOME/.local/bin/hotkeys:$PATH"
export PATH

if command -v locale >/dev/null; then
  export LC_TIME="ru_RU.UTF-8"
  export LC_NUMERIC="en_US.UTF-8"
  export LC_ALL=
fi

export EDITOR="micro"
export TERMINAL="st"
[ -z "$DISPLAY" ] && export DISPLAY=127.0.0.1:0
export NODE_PATH=/usr/lib/node_modules:/usr/local/lib/node_modules
export BAT_PAGER="less -RS"
export QT_AUTO_SCREEN_SCALE_FACTOR=0

# $HOME/ Clean-up:
# https://wiki.archlinux.org/title/XDG_Base_Directory
# export HISTFILE="$HOME/.config/bash_history"
export RLWRAP_HOME="$HOME/.config"
export LESSHISTFILE="$HOME/.config/less_history"
export SQLITE_HISTORY="$HOME/.config/sqlite_history"
export PYTHON_HISTORY="$HOME/.config/python_history" # will work in python 1.13
export INPUTRC="$HOME/.config/inputrc"
export ZDOTDIR="$HOME/.config/zsh"
export NODE_REPL_HISTORY="$HOME/.config/node_repl_history"
export NPM_CONFIG_USERCONFIG="$HOME/.config/npmrc"
export PASSWORD_STORE_DIR="$HOME/.config/password-store/"
export CARGO_HOME="$HOME/.local/share/cargo"
export GOPATH="$HOME/.local/share/go"
export VIMINIT="source $HOME/.config/vim/vimrc"
export XINITRC="$HOME/.config/x11/xinitrc"
export XCOMPOSEFILE="$HOME/.config/x11/XCompose"
export XAUTHORITY="$HOME/.local/share/Xauthority"
export RUSTUP_HOME="$HOME/.local/share/rustup"
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java

# less/man colors
export LESS=-R
export LESS_TERMCAP_mb=$'\x1b[1;31m'
export LESS_TERMCAP_md=$'\x1b[1;36m'
export LESS_TERMCAP_me=$'\x1b[0m'
export LESS_TERMCAP_so=$'\x1b[1;44;33m'
export LESS_TERMCAP_se=$'\x1b[0m'
export LESS_TERMCAP_us=$'\x1b[1;32m'
export LESS_TERMCAP_ue=$'\x1b[0m'
export GROFF_NO_SGR=1

# ssh over gpg
export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
gpgconf --launch gpg-agent
gpg-connect-agent updatestartuptty /bye >/dev/null
